log_level: info
host: 0.0.0.0
port: 10000
tls_enabled: false
tls_cert:
tls_key:
models_path: /home/m/.spago
language_models:
  - source: it
    target: en
    model: Helsinki-NLP/opus-mt-it-en
  - source: en
    target: it
    model: Helsinki-NLP/opus-mt-en-it
  - source: de
    target: en
    model: Helsinki-NLP/opus-mt-de-en
  - source: en
    target: de
    model: Helsinki-NLP/opus-mt-en-de
