log_level: info
host: 0.0.0.0
port: 10000
tls_enabled: false
tls_cert:
tls_key:
models_path: /tmp/translator-models
language_models:
  - from: it
    to: en
    model: Helsinki-NLP/opus-mt-it-en
  - from: en
    to: it
    model: Helsinki-NLP/opus-mt-en-it
  - from: de
    to: en
    model: Helsinki-NLP/opus-mt-de-en
  - from: en
    to: de
    model: Helsinki-NLP/opus-mt-en-de
